name: cm-action
description: Simple action to trigger a new CM build
author: Mohammed Babelly  
inputs:
  cm-token:
    description: 'CM token'
    required: true
  app-id:
    description: 'CM app Id'
    required: true
  workflow-id:
    description: 'CM workflow Id'
    required: true   
  branch:
    description: 'Branch'
    required: true       
    default: 'master'
outputs:
  build-id:
    description: "The started build Id"
    value: ${{ steps.build-cm.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - run: echo BuildId ${{ inputs.app-id }}.
      shell: bash
    - id: build-cm
      run: |
        echo "build-id=$(echo $(curl -H "Content-Type: application/json" -H "x-auth-token: ${{ inputs.cm-token }}" --data '{ \
        "appId": "${{ inputs.app-id }}", \
        "workflowId": "${{ inputs.workflow-id }}", \
        "branch": "${{ inputs.branch }}"}' \
        https://api.codemagic.io/builds | \
        jq -r '.buildId'))" >> $GITHUB_OUTPUT
      shell: bash
